#!/usr/bin/env python3
"""Insert QS 2026 top 200 global universities into database"""
import sqlite3, os

DB = os.path.join(os.path.dirname(os.path.abspath(__file__)), "knowledge_base.db")

entries = [
(1,'麻省理工学院','Massachusetts Institute of Technology (MIT)','美国','北美','工程、计算机、物理、经济','96位诺贝尔奖得主'),
(2,'帝国理工学院','Imperial College London','英国','欧洲','工程、医学、科学','14位诺贝尔奖得主'),
(3,'斯坦福大学','Stanford University','美国','北美','计算机、工程、商科、生物','84位诺贝尔奖得主'),
(4,'牛津大学','University of Oxford','英国','欧洲','人文、医学、法律、科学','72位诺贝尔奖得主'),
(5,'哈佛大学','Harvard University','美国','北美','法律、商科、医学、政治','161位诺贝尔奖得主'),
(6,'剑桥大学','University of Cambridge','英国','欧洲','科学、工程、人文、数学','121位诺贝尔奖得主'),
(7,'苏黎世联邦理工学院','ETH Zurich','瑞士','欧洲','工程、科学、计算机','32位诺贝尔奖得主'),
(8,'新加坡国立大学','National University of Singapore','新加坡','亚洲','工程、计算机、医学、商科',''),
(9,'伦敦大学学院','UCL','英国','欧洲','医学、法律、建筑、教育','35位诺贝尔奖得主'),
(10,'加州理工学院','California Institute of Technology','美国','北美','物理、工程、天文','47位诺贝尔奖得主'),
(11,'香港大学','University of Hong Kong','中国香港','亚洲','医学、法律、商科、教育',''),
(12,'南洋理工大学','Nanyang Technological University','新加坡','亚洲','工程、材料、计算机、商科',''),
(13,'芝加哥大学','University of Chicago','美国','北美','经济、物理、法律、社科','100位诺贝尔奖得主'),
(14,'北京大学','Peking University','中国大陆','亚洲','人文、社科、理学、医学',''),
(15,'宾夕法尼亚大学','University of Pennsylvania','美国','北美','商科、医学、法律、工程',''),
(16,'康奈尔大学','Cornell University','美国','北美','工程、农业、酒店管理、兽医',''),
(17,'清华大学','Tsinghua University','中国大陆','亚洲','工程、计算机、经济、建筑',''),
(17,'加州大学伯克利分校','UC Berkeley','美国','北美','工程、计算机、物理、经济','114位诺贝尔奖得主'),
(19,'墨尔本大学','University of Melbourne','澳大利亚','澳洲','医学、法律、教育、工程',''),
(20,'新南威尔士大学','UNSW Sydney','澳大利亚','澳洲','工程、商科、计算机、法律',''),
(21,'耶鲁大学','Yale University','美国','北美','法律、人文、艺术、医学',''),
(22,'慕尼黑工业大学','Technical University of Munich','德国','欧洲','工程、计算机、物理、化学',''),
(22,'洛桑联邦理工学院','EPFL','瑞士','欧洲','工程、计算机、材料、物理',''),
(24,'约翰霍普金斯大学','Johns Hopkins University','美国','北美','医学、公共卫生、国际关系',''),
(25,'普林斯顿大学','Princeton University','美国','北美','数学、物理、经济、公共政策',''),
(26,'多伦多大学','University of Toronto','加拿大','北美','医学、计算机、工程、商科',''),
(27,'爱丁堡大学','University of Edinburgh','英国','欧洲','医学、法律、文学、科学',''),
(28,'悉尼大学','University of Sydney','澳大利亚','澳洲','医学、法律、工程、商科',''),
(29,'韩国科学技术院','KAIST','韩国','亚洲','工程、计算机、科学、商科',''),
(30,'复旦大学','Fudan University','中国大陆','亚洲','人文、社科、医学、经济',''),
(31,'伦敦国王学院',"King's College London",'英国','欧洲','医学、法律、人文、社科',''),
(32,'香港中文大学','Chinese University of Hong Kong','中国香港','亚洲','医学、商科、社科、工程',''),
(33,'纽约大学','New York University','美国','北美','商科、法律、艺术、社科',''),
(34,'不列颠哥伦比亚大学','University of British Columbia','加拿大','北美','工程、林业、医学、商科',''),
(35,'曼彻斯特大学','University of Manchester','英国','欧洲','工程、医学、科学、商科',''),
(36,'首尔国立大学','Seoul National University','韩国','亚洲','工程、医学、法律、社科',''),
(37,'上海交通大学','Shanghai Jiao Tong University','中国大陆','亚洲','工程、医学、船舶、计算机',''),
(38,'法国巴黎文理研究大学','Universite PSL','法国','欧洲','科学、工程、艺术、人文',''),
(39,'浙江大学','Zhejiang University','中国大陆','亚洲','工程、计算机、医学、农业',''),
(40,'巴黎理工学院','Institut Polytechnique de Paris','法国','欧洲','工程、科学、计算机、数学',''),
(41,'卡内基梅隆大学','Carnegie Mellon University','美国','北美','计算机、工程、商科、艺术',''),
(42,'东京大学','University of Tokyo','日本','亚洲','工程、科学、医学、法律',''),
(43,'代尔夫特理工大学','Delft University of Technology','荷兰','欧洲','工程、设计、计算机、建筑',''),
(44,'香港科技大学','Hong Kong University of Science and Technology','中国香港','亚洲','工程、商科、计算机、科学',''),
(45,'西北大学','Northwestern University','美国','北美','商科、工程、法律、新闻',''),
(46,'慕尼黑大学','LMU Munich','德国','欧洲','科学、医学、人文、法律',''),
(47,'澳洲国立大学','Australian National University','澳大利亚','澳洲','科学、社科、人文、法律',''),
(48,'昆士兰大学','University of Queensland','澳大利亚','澳洲','生物、医学、工程、环境',''),
(49,'伦敦政治经济学院','LSE','英国','欧洲','经济、政治、法律、社科',''),
(50,'京都大学','Kyoto University','日本','亚洲','科学、工程、医学、人文',''),
(51,'布里斯托大学','University of Bristol','英国','欧洲','工程、医学、科学、社科',''),
(52,'莫纳什大学','Monash University','澳大利亚','澳洲','医学、工程、商科、教育',''),
(53,'香港理工大学','Hong Kong Polytechnic University','中国香港','亚洲','工程、设计、酒店管理、商科',''),
(54,'西澳大学','University of Western Australia','澳大利亚','澳洲','工程、矿业、医学、科学',''),
(55,'阿姆斯特丹大学','University of Amsterdam','荷兰','欧洲','社科、人文、科学、法律',''),
(56,'中国科学技术大学','USTC China','中国大陆','亚洲','物理、化学、数学、计算机',''),
(57,'杜克大学','Duke University','美国','北美','医学、法律、商科、工程',''),
(58,'布朗大学','Brown University','美国','北美','人文、科学、工程、医学',''),
(59,'阿德莱德大学','University of Adelaide','澳大利亚','澳洲','工程、医学、科学、酿酒',''),
(60,'鲁汶大学','KU Leuven','比利时','欧洲','工程、医学、科学、法律',''),
(61,'密歇根大学安娜堡','University of Michigan-Ann Arbor','美国','北美','工程、商科、医学、法律',''),
(62,'南京大学','Nanjing University','中国大陆','亚洲','天文、地质、文学、物理',''),
(63,'海德堡大学','Heidelberg University','德国','欧洲','医学、科学、人文、法律',''),
(64,'加州大学洛杉矶分校','UCLA','美国','北美','电影、工程、医学、法律',''),
(65,'马来亚大学','Universiti Malaya','马来西亚','亚洲','工程、医学、科学、社科',''),
(66,'圣路易斯华盛顿大学','Washington University in St. Louis','美国','北美','医学、工程、商科、建筑',''),
(67,'东京工业大学','Tokyo Institute of Technology','日本','亚洲','工程、材料、计算机、科学',''),
(68,'武汉大学','Wuhan University','中国大陆','亚洲','测绘、法学、生物、遥感',''),
(69,'柏林自由大学','Free University of Berlin','德国','欧洲','人文、社科、科学、医学',''),
(70,'隆德大学','Lund University','瑞典','欧洲','工程、医学、科学、法律',''),
(71,'奥克兰大学','University of Auckland','新西兰','澳洲','工程、医学、教育、商科',''),
(72,'柏林洪堡大学','Humboldt University of Berlin','德国','欧洲','人文、科学、法律、医学',''),
(73,'天主教鲁汶大学','Universite catholique de Louvain','比利时','欧洲','医学、工程、科学、法律',''),
(74,'华威大学','University of Warwick','英国','欧洲','商科、工程、数学、经济',''),
(75,'大阪大学','Osaka University','日本','亚洲','工程、医学、科学、人文',''),
(76,'格拉斯哥大学','University of Glasgow','英国','欧洲','医学、法律、科学、工程',''),
(77,'哥本哈根大学','University of Copenhagen','丹麦','欧洲','科学、医学、人文、法律',''),
(78,'佐治亚理工学院','Georgia Institute of Technology','美国','北美','工程、计算机、科学、商科',''),
(79,'哈尔滨工业大学','Harbin Institute of Technology','中国大陆','亚洲','航天、机械、计算机、土木',''),
(80,'伊利诺伊大学香槟分校','UIUC','美国','北美','工程、计算机、商科、农业',''),
(81,'索邦大学','Sorbonne University','法国','欧洲','科学、医学、人文、艺术',''),
(82,'德克萨斯大学奥斯汀','University of Texas at Austin','美国','北美','工程、计算机、商科、法律',''),
(83,'博特拉大学','Universiti Putra Malaysia','马来西亚','亚洲','农业、工程、医学、科学',''),
(84,'南安普顿大学','University of Southampton','英国','欧洲','工程、计算机、海洋、医学',''),
(85,'利兹大学','University of Leeds','英国','欧洲','商科、工程、医学、艺术',''),
(86,'加州大学圣地亚哥分校','UC San Diego','美国','北美','生物、工程、计算机、海洋',''),
(87,'东北大学（日本）','Tohoku University','日本','亚洲','工程、材料、科学、医学',''),
(88,'伯明翰大学','University of Birmingham','英国','欧洲','医学、工程、商科、法律',''),
(89,'达勒姆大学','Durham University','英国','欧洲','人文、科学、商科、法律',''),
(90,'宾夕法尼亚州立大学','Pennsylvania State University','美国','北美','工程、农业、地球科学、商科',''),
(91,'名古屋大学','Nagoya University','日本','亚洲','物理、化学、工程、医学',''),
(92,'南方科技大学','Southern University of Science and Technology','中国大陆','亚洲','理工、电子、计算机、材料',''),
(93,'圣安德鲁斯大学','University of St Andrews','英国','欧洲','人文、科学、神学、医学',''),
(94,'普渡大学','Purdue University','美国','北美','工程、计算机、农业、航空',''),
(95,'马来西亚国民大学','Universiti Kebangsaan Malaysia','马来西亚','亚洲','工程、医学、科学、社科',''),
(96,'谢菲尔德大学','University of Sheffield','英国','欧洲','工程、材料、医学、社科',''),
(97,'俄亥俄州立大学','Ohio State University','美国','北美','工程、商科、医学、农业',''),
(98,'都柏林圣三一学院','Trinity College Dublin','爱尔兰','欧洲','人文、科学、医学、工程',''),
(99,'智利天主教大学','Pontificia Universidad Catolica de Chile','智利','南美','工程、社科、医学、科学',''),
(100,'波士顿大学','Boston University','美国','北美','商科、法律、工程、医学',''),
(101,'加州大学戴维斯分校','UC Davis','美国','北美','农业、生物、兽医、工程',''),
(102,'浦项科技大学','POSTECH','韩国','亚洲','工程、材料、计算机、科学',''),
(103,'香港城市大学','City University of Hong Kong','中国香港','亚洲','工程、商科、计算机、创意媒体',''),
(104,'阿卜杜勒阿齐兹国王大学','King Abdulaziz University','沙特阿拉伯','亚洲','工程、医学、科学、海洋',''),
(105,'阿姆斯特丹自由大学','Vrije Universiteit Amsterdam','荷兰','欧洲','社科、医学、科学、法律',''),
(106,'乌得勒支大学','Utrecht University','荷兰','欧洲','科学、医学、人文、法律',''),
(107,'北京理工大学','Beijing Institute of Technology','中国大陆','亚洲','兵器、车辆、机械、计算机',''),
(108,'根特大学','Ghent University','比利时','欧洲','生物、工程、医学、农业',''),
(109,'阿尔托大学','Aalto University','芬兰','欧洲','工程、艺术、设计、商科',''),
(110,'莱顿大学','Leiden University','荷兰','欧洲','医学、法律、人文、科学',''),
(111,'华沙大学','University of Warsaw','波兰','欧洲','人文、科学、法律、经济',''),
(112,'马来西亚理工大学','Universiti Teknologi Malaysia','马来西亚','亚洲','工程、计算机、科学、教育',''),
(113,'格罗宁根大学','University of Groningen','荷兰','欧洲','医学、科学、经济、法律',''),
(114,'圣母大学','University of Notre Dame','美国','北美','法律、商科、神学、工程',''),
(115,'华中科技大学','Huazhong University of Science and Technology','中国大陆','亚洲','机械、光电、计算机、医学',''),
(116,'圣保罗大学','Universidade de Sao Paulo','巴西','南美','工程、医学、法律、科学',''),
(117,'诺丁汉大学','University of Nottingham','英国','欧洲','工程、医学、法律、社科',''),
(118,'巴塞尔大学','University of Basel','瑞士','欧洲','医学、科学、人文、法律',''),
(119,'中山大学','Sun Yat-sen University','中国大陆','亚洲','医学、管理、生态、哲学',''),
(120,'亚琛工业大学','RWTH Aachen University','德国','欧洲','工程、计算机、科学、机械',''),
(121,'伍伦贡大学','University of Wollongong','澳大利亚','澳洲','工程、计算机、商科、科学',''),
(122,'阿尔伯塔大学','University of Alberta','加拿大','北美','工程、医学、石油、农业',''),
(123,'麦克马斯特大学','McMaster University','加拿大','北美','医学、工程、科学、商科',''),
(124,'卡尔斯鲁厄理工学院','Karlsruhe Institute of Technology','德国','欧洲','工程、计算机、科学、能源',''),
(125,'莫斯科国立大学','Lomonosov Moscow State University','俄罗斯','欧洲','科学、人文、法律、工程',''),
(126,'日内瓦大学','University of Geneva','瑞士','欧洲','科学、医学、法律、国际关系',''),
(127,'纽约州立大学石溪分校','Stony Brook University','美国','北美','物理、数学、计算机、医学',''),
(128,'庞培法布拉大学','Universitat Pompeu Fabra','西班牙','欧洲','社科、人文、经济、法律',''),
(129,"西安交通大学","Xi'an Jiaotong University",'中国大陆','亚洲','电气、动力、机械、管理',''),
(130,'蒙特利尔大学','Universite de Montreal','加拿大','北美','医学、工程、科学、艺术',''),
(131,'埃因霍温理工大学','Eindhoven University of Technology','荷兰','欧洲','工程、设计、计算机、科学',''),
(132,'哥本哈根商学院','Copenhagen Business School','丹麦','欧洲','商科、经济、管理、金融',''),
(133,'皇家理工学院','KTH Royal Institute of Technology','瑞典','欧洲','工程、计算机、建筑、能源',''),
(134,'查尔姆斯理工大学','Chalmers University of Technology','瑞典','欧洲','工程、计算机、科学、建筑',''),
(135,'麦吉尔大学','McGill University','加拿大','北美','医学、法律、工程、商科',''),
(136,'约克大学（英国）','University of York','英国','欧洲','人文、社科、科学、医学',''),
(137,'马德里自治大学','Universidad Autonoma de Madrid','西班牙','欧洲','科学、医学、法律、哲学',''),
(138,'加州大学圣巴巴拉分校','UC Santa Barbara','美国','北美','工程、物理、材料、环境',''),
(139,'印度理工学院孟买','IIT Bombay','印度','亚洲','工程、计算机、科学、设计',''),
(140,'巴塞罗那大学','University of Barcelona','西班牙','欧洲','科学、医学、人文、经济',''),
(141,'开普敦大学','University of Cape Town','南非','非洲','医学、工程、科学、商科',''),
(142,'布鲁塞尔自由大学','Vrije Universiteit Brussel','比利时','欧洲','工程、医学、科学、社科',''),
(143,'斯德哥尔摩大学','Stockholm University','瑞典','欧洲','科学、人文、法律、社科',''),
(144,'印度科学院','Indian Institute of Science','印度','亚洲','科学、工程、计算机、材料',''),
(145,'天津大学','Tianjin University','中国大陆','亚洲','化工、精仪、建筑、管理',''),
(146,'挪威科技大学','NTNU','挪威','欧洲','工程、科学、医学、建筑',''),
(147,'北京师范大学','Beijing Normal University','中国大陆','亚洲','教育、心理、中文、地理',''),
(148,'加州大学欧文分校','UC Irvine','美国','北美','医学、工程、计算机、法律',''),
(149,'拉彭兰塔-拉赫蒂理工大学','LUT University','芬兰','欧洲','工程、能源、环境、科学',''),
(150,'蒙特雷科技大学','Tecnologico de Monterrey','墨西哥','北美','工程、商科、计算机、科学',''),
(151,'达特茅斯学院','Dartmouth College','美国','北美','工程、商科、医学、人文',''),
(152,'都柏林大学','University College Dublin','爱尔兰','欧洲','商科、工程、医学、科学',''),
(153,'佛罗里达大学','University of Florida','美国','北美','工程、商科、农业、医学',''),
(154,'贝尔格莱德大学','University of Belgrade','塞尔维亚','欧洲','工程、医学、科学、法律',''),
(155,'奥胡斯大学','Aarhus University','丹麦','欧洲','科学、医学、人文、商科',''),
(156,'贝鲁特美国大学','American University of Beirut','黎巴嫩','亚洲','医学、工程、商科、科学',''),
(157,'悉尼科技大学','University of Technology Sydney','澳大利亚','澳洲','计算机、工程、商科、设计',''),
(158,'厦门大学','Xiamen University','中国大陆','亚洲','海洋、经济、化学、统计',''),
(159,'科廷大学','Curtin University','澳大利亚','澳洲','工程、矿业、石油、商科',''),
(160,'滑铁卢大学','University of Waterloo','加拿大','北美','计算机、工程、数学、科技',''),
(161,'纽卡斯尔大学（英国）','Newcastle University','英国','欧洲','医学、工程、科学、人文',''),
(162,'维也纳大学','University of Vienna','奥地利','欧洲','人文、科学、法律、医学',''),
(163,'特拉维夫大学','Tel Aviv University','以色列','亚洲','科学、计算机、医学、法律',''),
(164,'明尼苏达大学','University of Minnesota','美国','北美','工程、医学、科学、法律',''),
(165,'波恩大学','University of Bonn','德国','欧洲','科学、数学、经济、法律',''),
(166,'伊斯法罕理工大学','Isfahan University of Technology','伊朗','亚洲','工程、计算机、科学、农业',''),
(167,'庆熙大学','Kyung Hee University','韩国','亚洲','医学、工程、社科、艺术',''),
(168,'高丽大学','Korea University','韩国','亚洲','法律、医学、工程、商科',''),
(169,'印度理工学院德里','IIT Delhi','印度','亚洲','工程、计算机、科学、商科',''),
(170,'卧龙岗大学','University of Wollongong','澳大利亚','澳洲','工程、计算机、科学、商科',''),
(171,'柏林工业大学','TU Berlin','德国','欧洲','工程、计算机、经济、规划',''),
(172,'成均馆大学','Sungkyunkwan University','韩国','亚洲','工程、医学、计算机、社科',''),
(173,'华中师范大学','Central China Normal University','中国大陆','亚洲','政治、教育、历史、心理',''),
(174,'维多利亚大学（加拿大）','University of Victoria','加拿大','北美','工程、计算机、海洋、科学',''),
(175,'欧洲大学学院','European University Institute','意大利','欧洲','经济、政治、法律、历史',''),
(176,'华东师范大学','East China Normal University','中国大陆','亚洲','教育、地理、软件、统计',''),
(177,'波尔图大学','University of Porto','葡萄牙','欧洲','工程、科学、医学、经济',''),
(178,'理海大学','Lehigh University','美国','北美','工程、商科、科学、教育',''),
(179,'亚利桑那大学','University of Arizona','美国','北美','天文、地质、工程、商科',''),
(180,'南开大学','Nankai University','中国大陆','亚洲','经济、数学、化学、历史',''),
(181,'洛约拉大学','Loyola University','美国','北美','商科、医学、法律、工程',''),
(182,'坎特伯雷大学','University of Canterbury','新西兰','澳洲','工程、科学、商科、人文',''),
(183,'埃尔朗根-纽伦堡大学','FAU Erlangen-Nuremberg','德国','欧洲','工程、医学、科学、经济',''),
(184,'汉阳大学','Hanyang University','韩国','亚洲','工程、建筑、医学、商科',''),
(185,'托木斯克国立大学','Tomsk State University','俄罗斯','欧洲','科学、工程、社科、人文',''),
(186,'西蒙弗雷泽大学','Simon Fraser University','加拿大','北美','计算机、工程、商科、社科',''),
(187,'加泰罗尼亚理工大学','Universitat Politecnica de Catalunya','西班牙','欧洲','工程、建筑、计算机、科学',''),
(188,'洛斯安第斯大学','Universidad de los Andes','哥伦比亚','南美','工程、管理、法律、医学',''),
(189,'北京航空航天大学','Beihang University','中国大陆','亚洲','航空、计算机、材料、仪器',''),
(190,'印度理工学院马德拉斯','IIT Madras','印度','亚洲','工程、计算机、科学、设计',''),
(191,"英国女王大学","Queen's University Belfast",'英国','欧洲','工程、医学、法律、人文',''),
(192,'赫尔辛基大学','University of Helsinki','芬兰','欧洲','医学、科学、人文、法律',''),
(193,'莱斯特大学','University of Leicester','英国','欧洲','医学、科学、法律、工程',''),
(194,'萨斯喀彻温大学','University of Saskatchewan','加拿大','北美','农业、医学、工程、科学',''),
(195,'迈阿密大学','University of Miami','美国','北美','医学、商科、工程、法律',''),
(196,'萨里大学','University of Surrey','英国','欧洲','工程、计算机、商科、健康',''),
(197,'弗赖堡大学','University of Freiburg','德国','欧洲','科学、医学、人文、法律',''),
(198,'斯威本科技大学','Swinburne University of Technology','澳大利亚','澳洲','工程、计算机、商科、设计',''),
(199,'国立台湾大学','National Taiwan University (NTU)','中国台湾','亚洲','工程、医学、科学、法律',''),
(200,'卡尔加里大学','University of Calgary','加拿大','北美','工程、石油、医学、商科',''),
]

# 去重（保持最后出现的条目）
seen = {}
for item in entries:
    seen[item[0]] = item  # 同名次覆盖
deduped = sorted(seen.values(), key=lambda x: x[0])

conn = sqlite3.connect(DB)
c = conn.cursor()

c.execute("""
    CREATE TABLE IF NOT EXISTS qs_global_rankings (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        rank_qs INTEGER,
        name_cn TEXT,
        name_en TEXT,
        country TEXT,
        region TEXT,
        key_disciplines TEXT,
        notable_alumni TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
""")
c.execute("DELETE FROM qs_global_rankings")

for item in deduped:
    c.execute("INSERT INTO qs_global_rankings (rank_qs, name_cn, name_en, country, region, key_disciplines, notable_alumni) VALUES (?,?,?,?,?,?,?)", item)

# 更新中国高校的QS排名
c.execute("""
    UPDATE universities SET rank_qs = (
        SELECT q.rank_qs FROM qs_global_rankings q 
        WHERE q.name_cn = universities.name
    )
""")

conn.commit()

c.execute("SELECT COUNT(*) FROM qs_global_rankings")
total = c.fetchone()[0]
c.execute("SELECT region, COUNT(*) FROM qs_global_rankings GROUP BY region ORDER BY COUNT(*) DESC")
print(f"QS全球排名表创建完成：{total} 所大学")
print()
for r, cnt in c.fetchall():
    print(f"  {r}: {cnt}所")
c.execute("SELECT COUNT(*) FROM universities WHERE rank_qs IS NOT NULL")
updated = c.fetchone()[0]
print(f"\n已更新中国高校QS排名：{updated}所")
conn.close()
